<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>Анализатор страниц</title>
</head>
<body class="h-dvh flex flex-col">
    <header class="flex bg-gray-700 p-2">
        <div class="flex justify-start items-center">
            <p class="text-white text-2xl mr-4">Анализатор страниц</p>
            <nav class="flex justify-center items-center gap-2">
                <a href="/" class="text-gray-400 hover:text-gray-200 text-base">Главная</a>
                <a href="/urls" class="text-gray-400 hover:text-gray-200 text-base">Сайты</a>
            </nav>
        </div>
    </header>

    <main>
        <section class="bg-gray-700">
            <h1>Анализатор страниц</h1>
            <p>Бесплатно проверяйте сайты на SEO пригодность</p>
        </section>
    </main>

    <footer class="bg-gray-200 mt-auto p-2">
        <div class="flex justify-center items-center">
            <a href="https://github.com/ArtMan-8" class="underline underline-offset-2 text-blue-600 hover:text-blue-900">@ArtMan-8</a>
        </div>
    </footer>
</body>
</html>